# Python parameters
use_csv: True
wpt_path: '/path/to/waypoint/csv/file.csv'
wpt_xind: 0
wpt_yind: 1
wpt_vind: 2
lookahead_distance: 0.9
wheelbase: 0.32

# ROS 2 parameters
pure_pursuit:
  ros__parameters:
    use_csv: True
    wpt_path: '/path/to/waypoint/csv/file.csv'
    wpt_xind: 0
    wpt_yind: 1
    wpt_vind: 2
    lookahead_distance: 0.9
    wheelbase: 0.32